# server port ?? ??
server:
  port: 8090

# data base ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_outstagarm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_outstagram
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: fluer7123@gmail.com
    password: eoljzrvjllyjomwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # thymeleaf ?? ??
  thymeleaf:
    cache: false

  # file size
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

# db query log ?? ??
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
cos:
  key: cos1234

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 483c5fda5520fe4ac417eb418b63af8b
            client-secret: R0JWWsM65JcTVLNHUV7BbxNED6akiH5v
            redirect-uri: http://localhost:8090/oauth/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
                - profile_nickname
                - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id






